"""AeroShield - Alembic environment (async).

Two things here are not boilerplate:

1. The URL comes from app.core.config.settings, not alembic.ini, so there is one
   source of truth and no credential in a committed file.

2. include_object filters out PostGIS's own tables. The postgis extension creates
   `spatial_ref_sys` (and geography_columns/geometry_columns views), which are not
   ours. Without this filter, `alembic revision --autogenerate` cheerfully writes a
   migration that DROPS spatial_ref_sys - which breaks every coordinate transform in
   the database.
"""

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from app.core.config import settings

# Importing the model registry is what populates Base.metadata. A model that is not
# imported here is invisible to autogenerate.
from app.db.base import Base
from app.db.models import ApiKey, Detection, Mission  # noqa: F401

config = context.config
config.set_main_option("sqlalchemy.url", settings.database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# Tables and indexes owned by the postgis extension, never by us.
POSTGIS_TABLES = {"spatial_ref_sys", "geography_columns", "geometry_columns", "raster_columns",
                  "raster_overviews", "topology", "layer"}


def include_object(object_, name, type_, reflected, compare_to):
    """Keep PostGIS's own objects out of every autogenerated migration."""
    if type_ == "table" and name in POSTGIS_TABLES:
        return False
    # geoalchemy2 manages the spatial index on `geog` through the column definition;
    # ours is declared explicitly in __table_args__, so any *reflected* index with
    # the geoalchemy2 default name is a leftover we should not try to recreate.
    if type_ == "index" and reflected and name and name.startswith("idx_") and "geog" in name:
        return False
    return True


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it - `alembic upgrade head --sql`."""
    context.configure(
        url=settings.database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
        # Catch column type changes, not just added/dropped columns.
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations through the asyncpg driver the app itself uses."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
