import { useEffect, useState } from 'react'
import { AlertTriangle, FlaskConical } from 'lucide-react'
import type { Detection, StreamState, Telemetry } from '@/types'
import { MISSION } from '@/lib/mockData'
import { formatZulu } from '@/lib/geo'
import { countByRisk } from '@/hooks/useDetections'
import { Badge } from '@/components/ui/Badge'

/**
 * StatusRail — the 44px band that answers "what am I looking at, and is it real?"
 *
 * The SIMULATED marker is not a debug affordance; it is a safety feature. This
 * console shows hazard positions, and every value in it is currently synthetic, so
 * the provenance sits in the most persistent piece of chrome on screen rather than
 * in a dismissible banner.
 */
export function StatusRail({
  telemetry,
  detections,
  streamState,
}: {
  telemetry: Telemetry | null
  detections: Detection[]
  streamState: StreamState
}) {
  const counts = countByRisk(detections)

  return (
    <header className="flex h-status shrink-0 items-center gap-3 border-b border-rule bg-ink-deep px-3">
      {/* Wordmark: the 'shield' set apart by weight, not by a logo mark. */}
      <div className="flex shrink-0 items-baseline gap-px font-display text-[15px] uppercase tracking-[0.16em]">
        <span className="font-bold text-paper">Aero</span>
        <span className="font-medium text-paper-dim">Shield</span>
      </div>

      <span className="hidden h-4 w-px bg-rule sm:block" aria-hidden />

      {/* Mission identity */}
      <div className="hidden min-w-0 items-baseline gap-2 sm:flex">
        <span className="font-mono text-[11px] tracking-[0.08em] text-paper">{MISSION.name}</span>
        <span className="truncate text-[11px] text-paper-faint">{MISSION.site}</span>
      </div>

      <div className="flex-1" />

      {/* Detection tallies — the standing count of what's out there. */}
      <div className="hidden items-center gap-1.5 md:flex">
        {counts.hazard > 0 && <Badge risk="hazard">{counts.hazard} hazard</Badge>}
        {counts.caution > 0 && <Badge risk="caution">{counts.caution} unverified</Badge>}
        {counts.cleared > 0 && <Badge risk="cleared">{counts.cleared} cleared</Badge>}
      </div>

      <StreamIndicator state={streamState} />

      {/* The provenance marker. Never hidden, never dismissible. */}
      <span
        className="flex shrink-0 items-center gap-1.5 border border-caution/50 bg-caution/10 px-1.5 py-px font-mono text-[10px] uppercase tracking-[0.1em] text-caution"
        title="All telemetry, detections, and reports on screen are generated by a client-side simulator. No real sensor or model output is present."
      >
        <FlaskConical size={11} strokeWidth={2} aria-hidden />
        Simulated
      </span>

      <Clock iso={telemetry?.timestamp ?? null} />
    </header>
  )
}

/** Stream health, distinct from the drone's radio link quality. */
function StreamIndicator({ state }: { state: StreamState }) {
  const config: Record<StreamState, { label: string; dot: string; text: string }> = {
    live: { label: 'Stream live', dot: 'bg-cleared', text: 'text-paper-dim' },
    connecting: { label: 'Connecting', dot: 'bg-caution', text: 'text-caution' },
    stalled: { label: 'Stream stalled', dot: 'bg-caution', text: 'text-caution' },
    offline: { label: 'Stream offline', dot: 'bg-hazard', text: 'text-hazard' },
  }
  const { label, dot, text } = config[state]

  return (
    <span className={`flex shrink-0 items-center gap-1.5 font-mono text-[10px] uppercase tracking-[0.1em] ${text}`}>
      <span className={`h-1.5 w-1.5 ${dot}`} aria-hidden />
      <span className="hidden lg:inline">{label}</span>
    </span>
  )
}

/**
 * Clock — mission time in Zulu, because that is what flight logs record and what
 * gets read out on radio. Falls back to local wall clock before first telemetry.
 */
function Clock({ iso }: { iso: string | null }) {
  const [now, setNow] = useState(() => new Date().toISOString())
  useEffect(() => {
    const t = setInterval(() => setNow(new Date().toISOString()), 1000)
    return () => clearInterval(t)
  }, [])

  return (
    <time
      className="shrink-0 font-mono text-[11px] tabular text-paper"
      dateTime={iso ?? now}
    >
      {formatZulu(iso ?? now)}
    </time>
  )
}

/**
 * AlertBanner — shown above the workspace when a new hazard-level detection
 * arrives. Says what happened and what to do; disappears on acknowledgement.
 */
export function AlertBanner({
  detection,
  onDismiss,
  onInspect,
}: {
  detection: Detection
  onDismiss: () => void
  onInspect: () => void
}) {
  return (
    <div
      role="alert"
      className="flex shrink-0 items-center gap-3 border-b border-hazard/60 bg-hazard/10 px-3 py-1.5"
    >
      <AlertTriangle size={14} className="shrink-0 text-hazard" aria-hidden />
      <p className="min-w-0 flex-1 truncate text-[11px] text-paper">
        <span className="font-mono tracking-[0.06em] text-hazard">{detection.id}</span>{' '}
        hazard-level detection in cell{' '}
        <span className="font-mono">{detection.gridCell}</span> — needs review before the
        ground team moves.
      </p>
      <button
        type="button"
        onClick={onInspect}
        className="shrink-0 border border-hazard/60 px-2 py-px font-display text-[10px] uppercase tracking-[0.1em] text-paper hover:bg-hazard/20"
      >
        Inspect
      </button>
      <button
        type="button"
        onClick={onDismiss}
        className="shrink-0 px-1 font-display text-[10px] uppercase tracking-[0.1em] text-paper-dim hover:text-paper"
      >
        Acknowledge
      </button>
    </div>
  )
}
