import type { ReactNode } from 'react'
import type { Detection, Mission, MissionReport } from '@/types'
import { CLASS_LABELS } from '@/types'
import { RISK_HEX, formatConfidence, riskOf } from '@/lib/risk'
import { M_PER_DEG_LAT, formatArea, formatDuration, formatLatLng, mPerDegLon } from '@/lib/geo'

/**
 * ReportPreview — the report as the document it will become.
 *
 * This is the one surface in the app rendered light-on-dark, and that is the point:
 * a report is a printed artifact that gets signed and filed, so previewing it in the
 * console's dark chrome would misrepresent what you are about to produce. The warm
 * `paper` tone from the palette finally appears as literal paper.
 *
 * The map plate is drawn as an SVG survey plate rather than a screenshot of the live
 * map, because a PDF has no tiles and printing dark imagery wastes ink and reads
 * badly. Ink-on-paper cartography is what belongs in a document.
 */
export function ReportPreview({
  report,
  mission,
  detections,
}: {
  report: MissionReport
  mission: Mission
  /** Only the detections in the report's register. */
  detections: Detection[]
}) {
  return (
    <div className="mx-auto w-full max-w-[820px]">
      {/*
        A4 proportion as a *minimum* height, not a fixed aspect ratio: the register
        grows with the mission, and a locked box would spill content outside the
        sheet. A real PDF paginates; a preview that keeps growing is the honest
        stand-in for that. `print-sheet` is what the print stylesheet isolates.
      */}
      <article
        className="print-sheet bg-[#F2EFE7] p-9 text-[#1A1F24] shadow-[0_10px_40px_rgba(0,0,0,0.5)]"
        style={{ minHeight: '1159px' }}
      >
        {/* Masthead */}
        <header className="flex items-start justify-between border-b-2 border-[#1A1F24] pb-2">
          <div>
            <p className="font-display text-[19px] font-bold uppercase tracking-[0.16em]">
              AeroShield
            </p>
            <p className="font-display text-[11px] uppercase tracking-[0.14em] text-[#4A5560]">
              Aerial survey report
            </p>
          </div>
          <div className="text-right">
            <p className="font-mono text-[11px]">{report.id}</p>
            <p
              className="mt-0.5 inline-block border px-1.5 py-px font-mono text-[9px] uppercase tracking-[0.1em]"
              style={{
                borderColor: report.status === 'final' ? '#1A1F24' : '#B0851F',
                color: report.status === 'final' ? '#1A1F24' : '#8A6614',
              }}
            >
              {report.status}
            </p>
          </div>
        </header>

        {/* Provenance banner — the loudest thing on the sheet, on purpose. */}
        <p
          className="mt-2 border-l-[3px] px-2 py-1 font-mono text-[9px] uppercase leading-snug tracking-[0.1em]"
          style={{ borderColor: RISK_HEX.hazard, background: '#F6E3E4', color: '#8C1A21' }}
        >
          Simulated data — generated by the AeroShield frontend for design purposes.
          Not a record of a real survey. Not for operational use.
        </p>

        {/* Metadata grid */}
        <section className="mt-3 grid grid-cols-4 gap-x-4 gap-y-2 border-b border-[#C9C3B5] pb-3">
          <Meta label="Mission" value={report.missionName} />
          <Meta label="Site" value={report.site} />
          <Meta label="Operator" value={report.generatedBy} />
          <Meta label="Generated" value={new Date(report.generatedAt).toISOString().slice(0, 16).replace('T', ' ') + 'Z'} />
          <Meta label="Area surveyed" value={formatArea(report.areaSurveyedM2)} />
          <Meta label="Coverage" value={`${report.coveragePct}%`} />
          <Meta label="Flight time" value={formatDuration(report.flightTimeS)} />
          <Meta label="Grid" value={`${mission.grid.cols}×${mission.grid.rows} @ ${mission.grid.cellSizeM} m`} />
        </section>

        {/* Summary */}
        <section className="mt-3">
          <SheetHeading>1. Summary</SheetHeading>
          <p className="mt-1 text-[11px] leading-relaxed">{report.summary}</p>
        </section>

        {/* Tallies */}
        <section className="mt-3">
          <SheetHeading>2. Detection tallies</SheetHeading>
          <div className="mt-1.5 grid grid-cols-5 border border-[#C9C3B5]">
            {[
              ['Total', report.tallies.total],
              ['Confirmed', report.tallies.confirmed],
              ['Flagged', report.tallies.flagged],
              ['Dismissed', report.tallies.dismissed],
              ['Unreviewed', report.tallies.unreviewed],
            ].map(([label, value], i) => (
              <div
                key={String(label)}
                className={`px-2 py-1.5 ${i > 0 ? 'border-l border-[#C9C3B5]' : ''}`}
              >
                <p className="font-display text-[9px] uppercase tracking-[0.12em] text-[#4A5560]">
                  {label}
                </p>
                <p className="font-display text-[17px] tabular">{value}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Map plate */}
        <section className="mt-3">
          <SheetHeading>3. Detection plate</SheetHeading>
          <MapPlate mission={mission} detections={detections} />
        </section>

        {/* Register */}
        <section className="mt-3">
          <SheetHeading>4. Detection register</SheetHeading>
          <table className="mt-1.5 w-full border-collapse">
            <thead>
              <tr className="border-b border-[#1A1F24]">
                {['ID', 'Cell', 'Class', 'Conf', 'Position', '±', 'Review'].map((h) => (
                  <th
                    key={h}
                    className="py-1 pr-2 text-left font-display text-[9px] uppercase tracking-[0.1em] text-[#4A5560]"
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {detections.slice(0, 12).map((d) => (
                <tr key={d.id} className="border-b border-[#DDD8CB]">
                  <td className="py-1 pr-2 font-mono text-[10px]">{d.id}</td>
                  <td className="py-1 pr-2 font-mono text-[10px]">{d.gridCell}</td>
                  <td className="py-1 pr-2 text-[10px]">{CLASS_LABELS[d.class]}</td>
                  <td className="py-1 pr-2 font-mono text-[10px] tabular">
                    {formatConfidence(d.confidence)}
                  </td>
                  <td className="py-1 pr-2 font-mono text-[10px] tabular">
                    {formatLatLng(d.position)}
                  </td>
                  <td className="py-1 pr-2 font-mono text-[10px] tabular">{d.positionErrorM}m</td>
                  <td className="py-1 pr-2 font-mono text-[10px] uppercase">{d.review.state}</td>
                </tr>
              ))}
            </tbody>
          </table>
          {detections.length > 12 && (
            <p className="mt-1 font-mono text-[9px] text-[#6A7580]">
              Showing 12 of {detections.length}. The full register is in the CSV export.
            </p>
          )}
        </section>

        {/* Limitations — a real report states its own bounds. */}
        <section className="mt-3">
          <SheetHeading>5. Limitations</SheetHeading>
          <ul className="mt-1 space-y-0.5 text-[10px] leading-relaxed">
            <li>
              RGB imagery detects surface indicators only. Buried items are outside this
              system's capability, and a nil return is not evidence of a clear area.
            </li>
            <li>
              Positions are projected from drone pose; treat the stated error radius as a
              search area rather than the coordinate as the object.
            </li>
            <li>
              Coverage figures describe ground imaged, not ground cleared. This report does
              not constitute clearance or release of land.
            </li>
          </ul>
        </section>

        {/* Sign-off */}
        <section className="mt-4 grid grid-cols-2 gap-6">
          {['Surveyed by', 'Reviewed by'].map((role) => (
            <div key={role}>
              <div className="h-7 border-b border-[#1A1F24]" />
              <p className="mt-1 font-display text-[9px] uppercase tracking-[0.12em] text-[#4A5560]">
                {role} · name, accreditation, date
              </p>
            </div>
          ))}
        </section>
      </article>
    </div>
  )
}

function SheetHeading({ children }: { children: ReactNode }) {
  return (
    <h3 className="border-b border-[#C9C3B5] pb-0.5 font-display text-[11px] uppercase tracking-[0.14em]">
      {children}
    </h3>
  )
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="font-display text-[9px] uppercase tracking-[0.12em] text-[#4A5560]">{label}</p>
      <p className="font-mono text-[10px] leading-tight">{value}</p>
    </div>
  )
}

/**
 * MapPlate — the survey block as ink on paper.
 *
 * Grid, cell references, and detection marks at their real relative positions.
 * Shape-coded exactly as the live map codes them (diamond confirmed, ring
 * unverified, dot cleared) so someone holding the printout and someone at the
 * console are reading the same notation.
 */
function MapPlate({ mission, detections }: { mission: Mission; detections: Detection[] }) {
  const { grid } = mission
  const W = 720
  const H = Math.round((W * grid.rows) / grid.cols)
  const cellW = W / grid.cols
  const cellH = H / grid.rows

  const blockWidthM = grid.cols * grid.cellSizeM
  const blockHeightM = grid.rows * grid.cellSizeM

  /** Detection position → plate coordinates, north-up. */
  const project = (d: Detection) => {
    const east = (d.position.lon - grid.origin.lon) * mPerDegLon(grid.origin.lat)
    const north = (d.position.lat - grid.origin.lat) * M_PER_DEG_LAT
    return {
      x: (east / blockWidthM) * W,
      // SVG y grows downward; the plate is north-up, so invert.
      y: H - (north / blockHeightM) * H,
    }
  }

  return (
    <div className="mt-1.5 border border-[#C9C3B5] bg-[#FAF8F2] p-2">
      <svg viewBox={`0 0 ${W} ${H}`} className="block w-full" role="img" aria-label="Detection plate">
        {/* Cells + references */}
        {Array.from({ length: grid.rows }, (_, row) =>
          Array.from({ length: grid.cols }, (_, col) => {
            const x = col * cellW
            const y = H - (row + 1) * cellH
            return (
              <g key={`${col}-${row}`}>
                <rect
                  x={x}
                  y={y}
                  width={cellW}
                  height={cellH}
                  fill="none"
                  stroke="#C9C3B5"
                  strokeWidth={1}
                />
                <text
                  x={x + 3}
                  y={y + 11}
                  fill="#A8A296"
                  fontFamily="IBM Plex Mono, monospace"
                  fontSize={8}
                >
                  {String.fromCharCode(65 + col)}
                  {row + 1}
                </text>
              </g>
            )
          }),
        )}

        {/* Planned path, for orientation. */}
        <polyline
          points={mission.plannedPath
            .map((p) => {
              const east = (p.lon - grid.origin.lon) * mPerDegLon(grid.origin.lat)
              const north = (p.lat - grid.origin.lat) * M_PER_DEG_LAT
              return `${(east / blockWidthM) * W},${H - (north / blockHeightM) * H}`
            })
            .join(' ')}
          fill="none"
          stroke="#B8B2A4"
          strokeWidth={1}
          strokeDasharray="4 4"
        />

        {/* Detection marks */}
        {detections.map((d) => {
          const { x, y } = project(d)
          const level = riskOf(d)
          const hex = level === 'cleared' ? '#3F7D6A' : level === 'hazard' ? '#B31E26' : '#8A6614'
          if (d.review.state === 'confirmed') {
            return (
              <rect
                key={d.id}
                x={x - 4}
                y={y - 4}
                width={8}
                height={8}
                fill={hex}
                transform={`rotate(45 ${x} ${y})`}
              />
            )
          }
          if (level === 'cleared') {
            return <circle key={d.id} cx={x} cy={y} r={2.5} fill={hex} />
          }
          return (
            <circle key={d.id} cx={x} cy={y} r={4.5} fill="none" stroke={hex} strokeWidth={1.8} />
          )
        })}

        {/* North arrow + scale — a plate without them is not a survey plate. */}
        <g transform={`translate(${W - 34}, 18)`}>
          <path d="M0 16 L0 0 M0 0 L-4 6 M0 0 L4 6" stroke="#1A1F24" strokeWidth={1.2} fill="none" />
          <text x={0} y={26} fill="#1A1F24" fontFamily="IBM Plex Mono, monospace" fontSize={8} textAnchor="middle">
            N
          </text>
        </g>
        <g transform={`translate(12, ${H - 14})`}>
          <line x1={0} y1={0} x2={cellW} y2={0} stroke="#1A1F24" strokeWidth={1.2} />
          <line x1={0} y1={-3} x2={0} y2={3} stroke="#1A1F24" strokeWidth={1.2} />
          <line x1={cellW} y1={-3} x2={cellW} y2={3} stroke="#1A1F24" strokeWidth={1.2} />
          <text x={cellW + 5} y={3} fill="#1A1F24" fontFamily="IBM Plex Mono, monospace" fontSize={8}>
            {grid.cellSizeM} m
          </text>
        </g>
      </svg>

      {/* Plate key */}
      <div className="mt-1.5 flex flex-wrap gap-3 font-mono text-[8px] uppercase tracking-[0.08em] text-[#4A5560]">
        <span className="flex items-center gap-1">
          <span className="h-2 w-2 rotate-45 bg-[#B31E26]" /> confirmed
        </span>
        <span className="flex items-center gap-1">
          <span className="h-2 w-2 rounded-full border-2 border-[#8A6614]" /> unverified
        </span>
        <span className="flex items-center gap-1">
          <span className="h-1.5 w-1.5 rounded-full bg-[#3F7D6A]" /> ruled out
        </span>
      </div>
    </div>
  )
}
