import type { Detection, Mission, MissionReport } from '@/types'
import { CLASS_LABELS } from '@/types'
import { riskOf } from './risk'

/**
 * Client-side export.
 *
 * Server-side PDF generation (WeasyPrint) is a backend concern that doesn't exist
 * yet, so these build the two formats that genuinely can be produced in the browser
 * and that a demining team would actually pass on: a CSV register for the office and
 * GeoJSON for whatever GIS the clearance organisation runs.
 *
 * Every export carries a provenance column/property marking the data as simulated.
 * An exported file outlives the UI that made it, so the warning has to travel with
 * the data rather than sit next to the download button.
 */

/** Trigger a browser download for generated text content. */
export function downloadText(filename: string, mime: string, content: string): void {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  // Revoke on the next tick so Safari has time to start the download.
  setTimeout(() => URL.revokeObjectURL(url), 0)
}

/** RFC 4180 field escaping — a reason field with a comma must not shift columns. */
function csvField(value: string | number): string {
  const s = String(value)
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

export function detectionsToCsv(detections: Detection[], mission: Mission): string {
  const header = [
    'detection_id',
    'mission',
    'grid_cell',
    'class',
    'class_label',
    'confidence',
    'risk_level',
    'review_state',
    'review_reason',
    'latitude',
    'longitude',
    'position_error_m',
    'capture_altitude_m',
    'captured_at',
    'data_source',
  ]

  const rows = detections.map((d) =>
    [
      d.id,
      mission.name,
      d.gridCell,
      d.class,
      CLASS_LABELS[d.class],
      d.confidence.toFixed(3),
      riskOf(d),
      d.review.state,
      d.review.reason ?? '',
      d.position.lat.toFixed(6),
      d.position.lon.toFixed(6),
      d.positionErrorM,
      d.captureAltitudeM.toFixed(1),
      d.capturedAt,
      // Travels with the file, deliberately.
      d.source === 'simulated' ? 'SIMULATED — not real sensor data' : 'backend',
    ]
      .map(csvField)
      .join(','),
  )

  return [header.join(','), ...rows].join('\r\n')
}

/**
 * GeoJSON FeatureCollection of detections.
 *
 * Points, not polygons, but each carries `position_error_m` so a GIS can buffer it
 * into the search area it really is. Exporting a bare point without the error would
 * hand the next team a false precision.
 */
export function detectionsToGeoJson(detections: Detection[], mission: Mission): string {
  const fc = {
    type: 'FeatureCollection' as const,
    metadata: {
      mission: mission.name,
      site: mission.site,
      operator: mission.operator,
      exportedAt: new Date().toISOString(),
      dataSource: 'SIMULATED — generated by the AeroShield frontend simulator, not a real survey',
      note: 'Positions are projected from drone pose. Buffer by position_error_m to obtain the search area.',
    },
    features: detections.map((d) => ({
      type: 'Feature' as const,
      geometry: {
        type: 'Point' as const,
        // GeoJSON is [lon, lat] — the reverse of how the UI shows it.
        coordinates: [Number(d.position.lon.toFixed(6)), Number(d.position.lat.toFixed(6))],
      },
      properties: {
        detection_id: d.id,
        grid_cell: d.gridCell,
        class: d.class,
        class_label: CLASS_LABELS[d.class],
        confidence: Number(d.confidence.toFixed(3)),
        risk_level: riskOf(d),
        review_state: d.review.state,
        review_reason: d.review.reason ?? null,
        position_error_m: d.positionErrorM,
        capture_altitude_m: d.captureAltitudeM,
        captured_at: d.capturedAt,
        data_source: d.source,
      },
    })),
  }
  return JSON.stringify(fc, null, 2)
}

/** Filename stem shared by every export of one report. */
export function exportStem(report: MissionReport): string {
  return `${report.missionName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${report.id.toLowerCase()}`
}
